"""
Sphinx Configuration for WTicket Documentation
============================================

A serverless ticket management system built with vanilla JavaScript
and JSONBin.io for zero-infrastructure deployment.

Author: William Rodriguez
LinkedIn: https://es.linkedin.com/in/wisrovi-rodriguez
"""

import os
import sys
from datetime import datetime

# -- Project Information -----------------------------------------------------

project = "WTicket"
copyright = f"{datetime.now().year}, William Rodriguez. All rights reserved."
author = "William Rodriguez"

# The full version, including alpha/beta/rc tags
release = "1.0.0"
version = "1.0"

# -- General Configuration --------------------------------------------------

# Add any Sphinx extension module names here
extensions = [
    "sphinx.ext.autodoc",  # Automatic documentation generation
    "sphinx.ext.napoleon",  # Google/NumPy style docstrings
    "sphinx.ext.viewcode",  # Add links to source code
    "sphinx.ext.intersphinx",  # Link to other Sphinx projects
    "sphinx.ext.todo",  # Todo items support
    "sphinx.ext.coverage",  # Coverage check
    "sphinx_copybutton",  # Copy button for code blocks
    "myst_parser",  # Markdown support
]

# Add any paths that contain templates here
templates_path = ["_templates"]

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**.inc",
    "**.bak",
]

# The reST default role (used for this markup: `text`) to use for all
# documents
default_role = "any"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    "canonical_url": "",
    "logo_only": False,
    "display_version": True,
    "prev_next_buttons": "bottom",
    "style_external_links": False,
    "style_nav_header_background": "#6366f1",
    "pygments_dark_style": "monokai",
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add any paths that contain custom themes here
html_theme_path = []

# The name of an image file (within the static path) to use as favicon
html_favicon = "_static/favicon.ico"

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ["_static"]

# Custom static files
html_css_files = [
    "css/custom.css",
]

# -- Options for HTML Help output -------------------------------------------

# Output file base name for HTML help builder
htmlhelp_basename = "WTicketdoc"

# -- Options for LaTeX output ----------------------------------------------

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, "WTicket.tex", "WTicket Documentation", "William Rodriguez", "manual"),
]

# -- Options for manual page output -----------------------------------------

# One entry per manual page
man_pages = [(master_doc, "wticket", "WTicket Documentation", [author], 1)]

# -- Options for Texinfo output ---------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (
        master_doc,
        "WTicket",
        "WTicket Documentation",
        author,
        "WTicket",
        "Serverless Ticket Management System",
        "Miscellaneous",
    ),
]

# -- Options for autodoc extension -------------------------------------------

# Extension settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "show-inheritance": True,
}

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    "javascript": ("https://developer.mozilla.org/en-US/docs/Web/JavaScript", None),
    "dom": (
        "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model",
        None,
    ),
}

# -- Options for todo extension ---------------------------------------------

todo_include_todos = True

# -- Source Suffix -----------------------------------------------------------

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- Redirects ---------------------------------------------------------------

# Create redirects for moved/renamed pages
html_redirect_pages = []

# -- Related resources -------------------------------------------------------

# GitHub settings
html_context = {
    "github_user": "wisrovi",
    "github_repo": "wticket",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

# --nitpicky mode -----------------------------------------------------------

# Raise errors for broken references (unused for now)
nitpicky = False

# -- Linkcheck --------------------------------------------------------------

# Check for broken links
linkcheck_timeout = 30
linkcheck_retries = 2
